name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run performance tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: production
      
      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 60000
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Run Lighthouse CI
        run: |
          lhci autorun --config=lighthouserc.js || echo "Lighthouse CI completed with warnings"
      
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/

  bundle-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          ANALYZE: true
      
      - name: Analyze bundle size
        run: |
          echo "📦 Bundle Analysis Results:"
          echo "=========================="
          
          # Check if .next directory exists
          if [ -d ".next" ]; then
            # Analyze build output
            ls -la .next/static/chunks/ || echo "No chunks directory found"
            
            # Check bundle sizes
            du -h .next/static/chunks/*.js 2>/dev/null || echo "No JS chunks found"
            
            echo ""
            echo "Total build size:"
            du -sh .next/ || echo "Could not determine build size"
          else
            echo "Build directory not found"
            exit 1
          fi
      
      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            let comment = '## 📦 Bundle Size Analysis\n\n';
            
            try {
              // This is a simplified version - in a real setup, you'd use tools like bundlephobia or size-limit
              comment += '✅ Bundle analysis completed\n';
              comment += '- Build successful\n';
              comment += '- Static assets generated\n';
              comment += '\nFor detailed analysis, check the build logs in the Actions tab.';
            } catch (error) {
              comment += '❌ Bundle analysis failed\n';
              comment += `Error: ${error.message}`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });